# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

xcodeproj 'Tomato.xcodeproj'

target "Tomato" do

pod 'AFNetworking', '~> 2.0'
pod 'SVProgressHUD', :head

end

target "TomatoTests" do

end

